id: A7AB1ABDE
title: 'The Rain of Enlightened Activity: A Prayer to the Gurus of the Lineage of
  the Vital Essence of the Aural Transmission Kīla'
type: translation
pechas:
- IE0D2E350
- ICCF89463
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:33:50.697110
  last_modified_at: 2023-01-04 12:33:50.697115
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IE0D2E350/7283: '6208'
  ICCF89463/F7A5: '6208'
